streamline formatting of shell scripts

diff --git a/packaging/env.sh.in b/packaging/env.sh.in
--- a/packaging/env.sh.in
+++ b/packaging/env.sh.in
@@ -1,14 +1,14 @@
 (return 0 2>/dev/null) || {
-    echo "The SciRooPlot env script must be sourced."
-    exit 1
+  echo "The SciRooPlot env script must be sourced."
+  exit 1
 }
 if [ -n "${BASH_VERSION:-}" ]; then
-    export SCIROOPLOT_ENV="${BASH_SOURCE[0]}"
+  export SCIROOPLOT_ENV="${BASH_SOURCE[0]}"
 elif [ -n "${ZSH_VERSION:-}" ]; then
-    export SCIROOPLOT_ENV="${(%):-%x}"
+  export SCIROOPLOT_ENV="${(%):-%x}"
 else
-    echo "Error: Unsupported shell. Please source SciRooPlot env script from bash or zsh."
-    return 1
+  echo "Error: Unsupported shell. Please source SciRooPlot env script from bash or zsh."
+  return 1
 fi
 export SCIROOPLOT_DATA_DIR="$(cd -- "$(dirname -- "${SCIROOPLOT_ENV}")" && pwd)"
 export SCIROOPLOT_ROOT="$(cd -- "${SCIROOPLOT_DATA_DIR}/../.." && pwd)"
@@ -33,13 +33,16 @@ function plot() {
   if [[ -d "${user_dir}" ]]; then
     local user_plotdef="$(${SCIROOPLOT_BIN}/srp confdir "@current")/plots.info"
     (
-      cd "${user_dir}";
-      if (( ! isPython )); then
-        err=$(cmake -S .. -B . 2>&1 >/dev/null) || { echo "${err}"; exit 1; }
-        (cmake --build . -j6 > /dev/null) || exit 1
+      cd "${user_dir}"
+      if ((!isPython)); then
+        err=$(cmake -S .. -B . 2>&1 >/dev/null) || {
+          echo "${err}"
+          exit 1
+        }
+        (cmake --build . -j6 >/dev/null) || exit 1
       fi
       if [[ ! -f "${user_plotdef}" || "${user_program}" -nt "${user_plotdef}" ]]; then
-        if (( isPython )); then
+        if ((isPython)); then
           if [ -n "${SCIROOPLOT_PYTHON_EXECUTABLE:-}" ]; then
             if [ ! -x "${SCIROOPLOT_PYTHON_EXECUTABLE}" ]; then
               echo "SciRooPlot's Python path is outdated and requires reinstall..."
@@ -47,7 +50,7 @@ function plot() {
             fi
             ${SCIROOPLOT_PYTHON_EXECUTABLE} "${user_program}"
           else
-              echo "Error: SciRooPlot was not compiled with Python bindings."
+            echo "Error: SciRooPlot was not compiled with Python bindings."
           fi
         else
           "${user_program}"
@@ -67,14 +70,14 @@ function srp() {
       conda update conda-forge::scirooplot
     else
       if [[ -z "${SCIROOPLOT_SOURCE_DIR:-}" || ! -d "${SCIROOPLOT_SOURCE_DIR}" ]]; then
-          echo "Error: SciRooPlot source directory not found."
-          echo "  SCIROOPLOT_SOURCE_DIR=${SCIROOPLOT_SOURCE_DIR:-<unset>}"
-          return 1
+        echo "Error: SciRooPlot source directory not found."
+        echo "  SCIROOPLOT_SOURCE_DIR=${SCIROOPLOT_SOURCE_DIR:-<unset>}"
+        return 1
       fi
       if [[ ! -f "${SCIROOPLOT_SOURCE_DIR}/scripts/install.sh" ]]; then
-          echo "Error: SciRooPlot installer not found:"
-          echo "  ${SCIROOPLOT_SOURCE_DIR}/scripts/install.sh"
-          return 1
+        echo "Error: SciRooPlot installer not found:"
+        echo "  ${SCIROOPLOT_SOURCE_DIR}/scripts/install.sh"
+        return 1
       fi
       if [[ -n "${2:-}" ]]; then
         "${SCIROOPLOT_SOURCE_DIR}/scripts/install.sh" "$2"
@@ -105,41 +108,42 @@ function srp() {
         fi
         if [[ -n "${opener:-}" ]]; then
           if command -v find >/dev/null 2>&1; then
-            if (( isPython )); then
-              find "${user_dir}/" -maxdepth 2 -type f \( -name '*.py' \)  -exec "${opener[@]}" {} +
+            if ((isPython)); then
+              find "${user_dir}/" -maxdepth 2 -type f \( -name '*.py' \) -exec "${opener[@]}" {} +
             else
-              find "${user_dir}/.." -maxdepth 2 -type f \( -name '*.cxx' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \)  -exec "${opener[@]}" {} +
+              find "${user_dir}/.." -maxdepth 2 -type f \( -name '*.cxx' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' \) -exec "${opener[@]}" {} +
             fi
             return 0
           fi
         fi
       fi
     fi
-    elif [[ "${1:-}" == "stats" ]]; then
-      local project_name="${2:-}"
-      local project_confdir="$(${SCIROOPLOT_BIN}/srp confdir "${project_name}")"
-      local n_plots=0
-      local n_inputs=0
-      local last_modified="-"
-      local tabcomp_file="${project_confdir}/tabcomp.csv"
-      if [[ -f "${tabcomp_file}" ]]; then
-          n_plots=$(wc -l < "${tabcomp_file}")
+  elif [[ "${1:-}" == "stats" ]]; then
+    local project_name="${2:-}"
+    local project_confdir="$(${SCIROOPLOT_BIN}/srp confdir "${project_name}")"
+    local n_plots=0
+    local n_inputs=0
+    local last_modified="-"
+    local tabcomp_file="${project_confdir}/tabcomp.csv"
+    if [[ -f "${tabcomp_file}" ]]; then
+      n_plots=$(wc -l <"${tabcomp_file}")
 
-          if [[ "$OSTYPE" == darwin* ]]; then
-              last_modified=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "${tabcomp_file}")
-          else
-              last_modified=$(stat -c "%y" "${tabcomp_file}" | cut -d'.' -f1)
-          fi
+      if [[ "$OSTYPE" == darwin* ]]; then
+        last_modified=$(stat -f "%Sm" -t "%Y-%m-%d %H:%M" "${tabcomp_file}")
+      else
+        last_modified=$(stat -c "%y" "${tabcomp_file}" | cut -d'.' -f1)
       fi
-      local datasources_file="${project_confdir}/dataSources.info"
-      if [[ -f "${datasources_file}" ]]; then
-          n_inputs=$(grep -c 'FILE' "${datasources_file}")
-      fi
-      printf "Plots          : %d\n" "${n_plots}"
-      printf "Input files    : %d\n" "${n_inputs}"
-      printf "Last modified  : %s\n" "${last_modified}"
+    fi
+    local datasources_file="${project_confdir}/dataSources.info"
+    if [[ -f "${datasources_file}" ]]; then
+      n_inputs=$(grep -c 'FILE' "${datasources_file}")
+    fi
+    printf "Plots          : %d\n" "${n_plots}"
+    printf "Input files    : %d\n" "${n_inputs}"
+    printf "Last modified  : %s\n" "${last_modified}"
   elif [[ "${1:-}" == "init-cpp" || "${1:-}" == "init-py" ]]; then
-    local isPython=0; [[ "${1:-}" == "init-py" ]] && isPython=1
+    local isPython=0
+    [[ "${1:-}" == "init-py" ]] && isPython=1
     local project_name="${2:-}"
     local project_path="${project_name}"
     [ -n "${3:-}" ] && project_path="${3:-}"
@@ -160,7 +164,7 @@ function srp() {
     fi
 
     mkdir -p "${project_path}"
-    if (( isPython )); then
+    if ((isPython)); then
       cp "${SCIROOPLOT_DATA_DIR}/user/DefinePlots.py" "${project_path}/"
       sed -i.bak "s/PROJECT_NAME/${project_name}/" "${project_path}/DefinePlots.py" && rm -f "${project_path}/DefinePlots.py.bak"
       "${SCIROOPLOT_BIN}/srp" "set" "${project_name}" "program" "${project_path}/DefinePlots.py"
@@ -171,7 +175,7 @@ function srp() {
         fi
         ${SCIROOPLOT_PYTHON_EXECUTABLE} "${project_path}/DefinePlots.py"
       else
-          echo "Error: SciRooPlot was not compiled with Python bindings."
+        echo "Error: SciRooPlot was not compiled with Python bindings."
       fi
     else
       cp "${SCIROOPLOT_DATA_DIR}/user/CMakeLists.txt" "${project_path}/"
@@ -180,7 +184,7 @@ function srp() {
       sed -i.bak "s/PROJECT_NAME/${project_name}/" "${project_path}/DefinePlots.cpp" && rm -f "${project_path}/DefinePlots.cpp.bak"
       mkdir -p "${project_path}/build"
       local curdir="$(pwd)"
-      cd "${project_path}/build" && cmake -Wno-dev .. > /dev/null 2>&1 && cmake --build . > /dev/null 2>&1 && ./definePlots
+      cd "${project_path}/build" && cmake -Wno-dev .. >/dev/null 2>&1 && cmake --build . >/dev/null 2>&1 && ./definePlots
       cd "${curdir}"
       "${SCIROOPLOT_BIN}/srp" "set" "${project_name}" "program" "${project_path}/build/definePlots"
     fi
@@ -190,14 +194,14 @@ function srp() {
   else
     args=("$@")
     [[ -n "${ZSH_VERSION:-}" ]] && setopt local_options KSH_ARRAYS
-    if (( ${#args[@]} >= 4 )) && [[ "${args[2]}" =~ ^(program|outdir)$ ]] && [[ "${args[3]}" != /* ]]; then
+    if ((${#args[@]} >= 4)) && [[ "${args[2]}" =~ ^(program|outdir)$ ]] && [[ "${args[3]}" != /* ]]; then
       args[3]="$(pwd)/${args[3]}"
     fi
-    if (( ${#args[@]} >= 1 )) && [[ "${args[0]}" =~ ^(add)$ ]]; then
-      if (( ${#args[@]} >= 3 ))  && [[ "${args[2]}" != /* ]]; then
+    if ((${#args[@]} >= 1)) && [[ "${args[0]}" =~ ^(add)$ ]]; then
+      if ((${#args[@]} >= 3)) && [[ "${args[2]}" != /* ]]; then
         args[2]="$(pwd)/${args[2]}"
       fi
-      if (( ${#args[@]} >= 4 ))  && [[ "${args[3]}" != /* ]]; then
+      if ((${#args[@]} >= 4)) && [[ "${args[3]}" != /* ]]; then
         args[3]="$(pwd)/${args[3]}"
       fi
     fi
@@ -226,8 +230,7 @@ _plot_completions_zsh() {
 
   # find all groups and store main groups separately
   local name_in group_in
-  while IFS="," read -r name_in group_in
-  do
+  while IFS="," read -r name_in group_in; do
     main_groups+=("${group_in%%/*}")
     groups+=("${group_in}")
   done < <(LC_ALL=C sort -t',' -k2,2 -u "${tabcomp_file}")
@@ -237,18 +240,16 @@ _plot_completions_zsh() {
     names=()
 
     local name_in group_in
-    while IFS="," read -r name_in group_in
-    do
+    while IFS="," read -r name_in group_in; do
       [[ "${group_in}" != "${group}" && "${group_in}" != "${group}/"* ]] && continue
       names+=("${name_in}")
-    done < <( grep "^.*,${group}" "${tabcomp_file}" )
+    done < <(grep "^.*,${group}" "${tabcomp_file}")
   }
 
   _arguments \
-    '1: :->group'\
-    '2: :->name'\
+    '1: :->group' \
+    '2: :->name' \
     '3: :->mode'
-
 
   case $state in
     group)
@@ -257,14 +258,14 @@ _plot_completions_zsh() {
       else
         _arguments '1:profiles:(${main_groups})'
       fi
-    ;;
+      ;;
     name)
       updatePlotNames "${words[2]}"
       _arguments '2:profiles:(${names})'
-    ;;
+      ;;
     mode)
       _arguments '3:profiles:(${modes})'
-    ;;
+      ;;
   esac
 
   unset -f updatePlotNames
@@ -288,22 +289,21 @@ _srp_completions_zsh() {
   if [[ -f "${project_file}" ]]; then
     projects=("@current")
     local project
-    while read -r project
-    do
+    while read -r project; do
       projects+=("${project}")
     done < <(grep -B1 '{' "${project_file}" | grep -v '{' | grep -v -- '^--$')
   fi
 
   _arguments \
-    '1: :->command'\
-    '2: :->project'\
-    '3: :->property'\
+    '1: :->command' \
+    '2: :->project' \
+    '3: :->property' \
     '4: :->setting'
 
   case "${state}" in
     command)
       _arguments '1:profiles:(${general_commands} ${project_commands} ${file_commands})'
-    ;;
+      ;;
     project)
       if [[ " ${project_commands[@]} " =~ " ${words[2]} " ]]; then
         _arguments '2:profiles:(${projects})'
@@ -320,19 +320,19 @@ _srp_completions_zsh() {
       elif [[ " matchcase " =~ " ${words[2]} " ]]; then
         _arguments '2:profiles:(${matchcase_settings})'
       fi
-    ;;
+      ;;
     property)
       if [[ " ${project_commands_with_prop[@]} " =~ " ${words[2]} " ]]; then
         _arguments '3:profiles:(${properties})'
       elif [[ "${words[2]}" == init-* ]]; then
         _files -/
       elif [[ "${words[2]}" == "add" ]]; then
-          _files -f
+        _files -f
       fi
-    ;;
+      ;;
     setting)
       if [[ "${words[2]}" == "add" ]]; then
-          _files -/
+        _files -/
       elif [[ "${words[2]}" == "set" ]]; then
         if [[ "${words[4]}" == "program" ]]; then
           _files -f
@@ -340,7 +340,7 @@ _srp_completions_zsh() {
           _files -/
         fi
       fi
-    ;;
+      ;;
   esac
 }
 
@@ -358,8 +358,7 @@ _plot_completions_bash() {
 
   # find all groups and store main groups separately
   local name_in group_in
-  while IFS="," read -r name_in group_in
-  do
+  while IFS="," read -r name_in group_in; do
     main_groups+=" ${group_in%%/*}"
     groups+=" ${group_in}"
   done < <(LC_ALL=C sort -t',' -k2,2 -u "${tabcomp_file}")
@@ -369,28 +368,27 @@ _plot_completions_bash() {
     names=()
 
     local name_in group_in
-    while IFS="," read -r name_in group_in
-    do
+    while IFS="," read -r name_in group_in; do
       [[ "${group_in}" != "${group}" && "${group_in}" != "${group}/"* ]] && continue
       names+=" ${name_in}"
-    done < <( grep "^.*,${group}" "${tabcomp_file}" )
+    done < <(grep "^.*,${group}" "${tabcomp_file}")
   }
 
   case "${COMP_CWORD}" in
-  1)
-    if [[ "${COMP_WORDS[COMP_CWORD]}" == *"/"* ]]; then
-      COMPREPLY=( $(compgen -W "${groups}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    else
-      COMPREPLY=( $(compgen -W "${main_groups}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    fi
-  ;;
-  2)
-    updatePlotNames "${COMP_WORDS[COMP_CWORD-1]}"
-    COMPREPLY=( $(compgen -W "${names}" -- "${COMP_WORDS[COMP_CWORD]}") )
-  ;;
-  3)
-    COMPREPLY=( $( compgen -W "${modes}" -- "${COMP_WORDS[COMP_CWORD]}" ) )
-  ;;
+    1)
+      if [[ "${COMP_WORDS[COMP_CWORD]}" == *"/"* ]]; then
+        COMPREPLY=($(compgen -W "${groups}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      else
+        COMPREPLY=($(compgen -W "${main_groups}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      fi
+      ;;
+    2)
+      updatePlotNames "${COMP_WORDS[COMP_CWORD - 1]}"
+      COMPREPLY=($(compgen -W "${names}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      ;;
+    3)
+      COMPREPLY=($(compgen -W "${modes}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      ;;
   esac
 
   unset -f updatePlotNames
@@ -414,74 +412,73 @@ _srp_completions_bash() {
   if [[ -f "${project_file}" ]]; then
     projects=("@current")
     local project
-    while read -r project
-    do
+    while read -r project; do
       projects+=("${project}")
     done < <(grep -B1 '{' "${project_file}" | grep -v '{' | grep -v -- '^--$')
   fi
 
   case "${COMP_CWORD}" in
-  1)
-    COMPREPLY=( $(compgen -W "${general_commands} ${project_commands} ${file_commands}" -- "${COMP_WORDS[COMP_CWORD]}") )
-  ;;
-  2)
-    if [[ " ${project_commands[@]} " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${projects[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ " ${file_commands[@]} " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      cur="${COMP_WORDS[COMP_CWORD]}"
-      while IFS= read -r d; do
-        COMPREPLY+=("${d}/")
-      done < <(compgen -d -- "${cur}")
-      while IFS= read -r f; do
-        [[ "${f}" == *.root ]] && COMPREPLY+=("${f}")
-      done < <(compgen -f -- "${cur}")
-    elif [[ " color " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${color_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ " verbosity " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${verbosity_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ " plotmode " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${plotmodes[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ " matchmode " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${matchmode_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ " matchcase " =~ " ${COMP_WORDS[COMP_CWORD-1]} " ]]; then
-      COMPREPLY=( $(compgen -W "${matchcase_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    else
-      COMPREPLY=( )
-    fi
-  ;;
-  3)
-    if [[ " ${project_commands_with_prop[@]} " =~ " ${COMP_WORDS[COMP_CWORD-2]} " ]]; then
-      COMPREPLY=( $(compgen -W "${properties}" -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ "${COMP_WORDS[COMP_CWORD-2]}" == init-* ]]; then
-      COMPREPLY=( $(compgen -d -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ "${COMP_WORDS[COMP_CWORD-2]}" == "add" ]]; then
-      COMPREPLY=( $(compgen -f -- "${COMP_WORDS[COMP_CWORD]}") )
-    else
-      COMPREPLY=( )
-    fi
-  ;;
-  4)
-    if [[ "${COMP_WORDS[COMP_CWORD-3]}" == "add" ]]; then
-      COMPREPLY=( $(compgen -d -- "${COMP_WORDS[COMP_CWORD]}") )
-    elif [[ "${COMP_WORDS[COMP_CWORD-3]}" == "set" ]]; then
-      case "${COMP_WORDS[COMP_CWORD-1]}" in
-        program)
-          COMPREPLY=( $(compgen -f -- "${COMP_WORDS[COMP_CWORD]}") )
-        ;;
-        outdir)
-          COMPREPLY=( $(compgen -d -- "${COMP_WORDS[COMP_CWORD]}") )
-        ;;
-      esac
-    fi
-  ;;
+    1)
+      COMPREPLY=($(compgen -W "${general_commands} ${project_commands} ${file_commands}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      ;;
+    2)
+      if [[ " ${project_commands[@]} " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${projects[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ " ${file_commands[@]} " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        cur="${COMP_WORDS[COMP_CWORD]}"
+        while IFS= read -r d; do
+          COMPREPLY+=("${d}/")
+        done < <(compgen -d -- "${cur}")
+        while IFS= read -r f; do
+          [[ "${f}" == *.root ]] && COMPREPLY+=("${f}")
+        done < <(compgen -f -- "${cur}")
+      elif [[ " color " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${color_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ " verbosity " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${verbosity_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ " plotmode " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${plotmodes[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ " matchmode " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${matchmode_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ " matchcase " =~ " ${COMP_WORDS[COMP_CWORD - 1]} " ]]; then
+        COMPREPLY=($(compgen -W "${matchcase_settings[*]}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      else
+        COMPREPLY=()
+      fi
+      ;;
+    3)
+      if [[ " ${project_commands_with_prop[@]} " =~ " ${COMP_WORDS[COMP_CWORD - 2]} " ]]; then
+        COMPREPLY=($(compgen -W "${properties}" -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ "${COMP_WORDS[COMP_CWORD - 2]}" == init-* ]]; then
+        COMPREPLY=($(compgen -d -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ "${COMP_WORDS[COMP_CWORD - 2]}" == "add" ]]; then
+        COMPREPLY=($(compgen -f -- "${COMP_WORDS[COMP_CWORD]}"))
+      else
+        COMPREPLY=()
+      fi
+      ;;
+    4)
+      if [[ "${COMP_WORDS[COMP_CWORD - 3]}" == "add" ]]; then
+        COMPREPLY=($(compgen -d -- "${COMP_WORDS[COMP_CWORD]}"))
+      elif [[ "${COMP_WORDS[COMP_CWORD - 3]}" == "set" ]]; then
+        case "${COMP_WORDS[COMP_CWORD - 1]}" in
+          program)
+            COMPREPLY=($(compgen -f -- "${COMP_WORDS[COMP_CWORD]}"))
+            ;;
+          outdir)
+            COMPREPLY=($(compgen -d -- "${COMP_WORDS[COMP_CWORD]}"))
+            ;;
+        esac
+      fi
+      ;;
   esac
 }
 
 if [ -n "${ZSH_VERSION}" ]; then
-  if ! command -v compinit &> /dev/null; then
+  if ! command -v compinit &>/dev/null; then
     autoload -U compinit compdef && compinit
   fi
-  if command -v compdef &> /dev/null; then
+  if command -v compdef &>/dev/null; then
     compdef _plot_completions_zsh plot
     compdef _srp_completions_zsh srp
   fi
